### ISSUE TITLE
QMP6988.py

### ISSUE THREAD

**Issue by lankylad9** [gandro/micropython-m5stamp-c3u#2] opened 2022-08-18 16:51 UTC
My SHT30 sensor in my  M5Stack ENV III Unit is correctly giving the temperature as 24c and the humidity as 52%

The QMP6988 sensor in the same M5Stack ENV III Unit on first call gives the temperature as 192c and pressure as -455667. Subsequent calls give the correct readings.

I have since discovered that leaving a one second wait before the QMP6988 call fixes the problem

**Comment by windsmiths** [comment] 2023-01-03 18:53
> My SHT30 sensor in my M5Stack ENV III Unit is correctly giving the temperature as 24c and the humidity as 52%
> 
> The QMP6988 sensor in the same M5Stack ENV III Unit on first call gives the temperature as 192c and pressure as -455667. Subsequent calls give the correct readings.
> 
> I have since discovered that leaving a one second wait before the QMP6988 call fixes the problem

Hi, when y using QMP6988 .p on pi pico W, I found that:
i) Device hung when using hardware I2C, didn't crash with software I2C
ii) I get incorrect readings for first call to qmp6988.measure() (191.8784, -454099.1), using SoftI2C.  Subsequent calls return correct call.

Not doing the SW Reset fixes first issue
Adding 1 second sleep at end of initialisation call fixes second issue.

**Comment by gandro** [comment] 2023-01-10 13:03
Thanks for the reports!

Yeah, Hardware I2C was known to be broken (see #1). Seems like it's fixed now, so might be worth trying again on a nightly build. I haven't tested it yet. https://github.com/micropython/micropython/issues/7772#issuecomment-1294679067

I'm not sure if the QMP6988 errors are due to the SoftI2C or if the sensor really needs a long time to boot up.

**Comment by gandro** [comment] 2023-01-15 15:55
Trying out HardI2C with the ESP32-C3U it seems that the software reset indeed causes problems with the Hardware I2C. I suspect because the device is not following proper I2C protocol after a reset. I'll add some error handling around the software reset routine to deal with that case (unless there is a better way, but if the device doesn't speak I2C properly after a reset, then there is not much that can be done).

Regarding the first measurement (191.8784, -454099.1) immediately after init - I can reproduce them as well. This seems to happen when the sensor is in normal mode and we're starting to read out the value, even though the measurement is not ready yet. Luckily, the code for waiting for a measurement already exists, it was just not enabled on normal mode. I've fixed the code to always wait for the measurement now as well.

I think I fixed both issues on the main branch, please take a look:

- [qmp6988: Fix invalid readings in normal mode](https://github.com/gandro/micropython-m5stamp-c3u/commit/937f54b835de9f0e2bc8d93457467ee7e09a1a8d)
- [qmp6988: Fix crash when soft-reset is performed](https://github.com/gandro/micropython-m5stamp-c3u/commit/fe3ddc3d0c09cca4096dcfc37bbbf57e7b4a1271)

**Closed as completed by gandro** 2023-01-15 15:55 UTC
